from __future__ import annotations

import argparse
import csv
import sys
from pathlib import Path
from typing import Iterable

from psycopg import sql
from psycopg.rows import dict_row

from export_postgres_ddl import quote_ident, safe_filename, set_search_path
from postgres_connector import connect_postgres


PROJECT_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_OUTPUT_DIR = PROJECT_ROOT / "data" / "postgresql" / "sql" / "dml" / "tables"
DEFAULT_TABLES = ("ticker_master", "mart_daily_price_raw")


def qualified_name(schema: str, table: str) -> str:
    return f"{quote_ident(schema)}.{quote_ident(table)}"


def header(title: str) -> str:
    return f"-- {title}\n-- Generated by scripts/db/export_postgres_dml.py\n\n"


def find_table(conn, table_name: str, schema_name: str | None) -> dict:
    with conn.cursor(row_factory=dict_row) as cur:
        if schema_name:
            cur.execute(
                """
                SELECT n.nspname AS schema_name, c.relname AS table_name
                FROM pg_class c
                JOIN pg_namespace n ON n.oid = c.relnamespace
                WHERE c.relkind IN ('r', 'p')
                  AND n.nspname = %(schema_name)s
                  AND c.relname = %(table_name)s
                """,
                {"schema_name": schema_name, "table_name": table_name},
            )
        else:
            cur.execute(
                """
                SELECT n.nspname AS schema_name, c.relname AS table_name
                FROM pg_class c
                JOIN pg_namespace n ON n.oid = c.relnamespace
                WHERE c.relkind IN ('r', 'p')
                  AND n.nspname NOT IN ('pg_catalog', 'information_schema')
                  AND n.nspname NOT LIKE %(pg_schema_pattern)s
                  AND c.relname = %(table_name)s
                ORDER BY
                    CASE WHEN n.nspname = 'stock_analysis' THEN 0 ELSE 1 END,
                    n.nspname
                """,
                {"table_name": table_name, "pg_schema_pattern": "pg\\_%"},
            )

        rows = cur.fetchall()
        if not rows:
            target = f"{schema_name}.{table_name}" if schema_name else table_name
            raise RuntimeError(f"Table not found: {target}")
        if len(rows) > 1 and not schema_name:
            names = ", ".join(f"{row['schema_name']}.{row['table_name']}" for row in rows)
            raise RuntimeError(f"Table name is ambiguous. Specify --schema. Matches: {names}")
        return rows[0]


def fetch_columns(conn, schema_name: str, table_name: str) -> list[str]:
    with conn.cursor(row_factory=dict_row) as cur:
        cur.execute(
            """
            SELECT a.attname AS column_name
            FROM pg_attribute a
            JOIN pg_class c ON c.oid = a.attrelid
            JOIN pg_namespace n ON n.oid = c.relnamespace
            WHERE n.nspname = %(schema_name)s
              AND c.relname = %(table_name)s
              AND a.attnum > 0
              AND NOT a.attisdropped
            ORDER BY a.attnum
            """,
            {"schema_name": schema_name, "table_name": table_name},
        )
        return [row["column_name"] for row in cur.fetchall()]


def fetch_primary_key_columns(conn, schema_name: str, table_name: str) -> list[str]:
    with conn.cursor(row_factory=dict_row) as cur:
        cur.execute(
            """
            SELECT a.attname AS column_name
            FROM pg_constraint con
            JOIN pg_class c ON c.oid = con.conrelid
            JOIN pg_namespace n ON n.oid = c.relnamespace
            JOIN unnest(con.conkey) WITH ORDINALITY key(attnum, ord) ON true
            JOIN pg_attribute a ON a.attrelid = c.oid AND a.attnum = key.attnum
            WHERE con.contype = 'p'
              AND n.nspname = %(schema_name)s
              AND c.relname = %(table_name)s
            ORDER BY key.ord
            """,
            {"schema_name": schema_name, "table_name": table_name},
        )
        return [row["column_name"] for row in cur.fetchall()]


def copy_value(value) -> str:
    if value is None:
        return r"\N"
    text = str(value)
    return (
        text.replace("\\", "\\\\")
        .replace("\t", "\\t")
        .replace("\r", "\\r")
        .replace("\n", "\\n")
    )


def export_table(conn, output_dir: Path, schema_name: str, table_name: str) -> int:
    columns = fetch_columns(conn, schema_name, table_name)
    primary_key_columns = fetch_primary_key_columns(conn, schema_name, table_name)
    filename = safe_filename(schema_name, table_name)
    output_path = output_dir / filename
    output_path.parent.mkdir(parents=True, exist_ok=True)

    column_identifiers = [sql.Identifier(column) for column in columns]
    order_columns = primary_key_columns or columns
    order_identifiers = [sql.Identifier(column) for column in order_columns]
    select_query = sql.SQL("SELECT {} FROM {} ORDER BY {}").format(
        sql.SQL(", ").join(column_identifiers),
        sql.Identifier(schema_name, table_name),
        sql.SQL(", ").join(order_identifiers),
    )

    row_count = 0
    with output_path.open("w", encoding="utf-8", newline="") as file:
        file.write(header(f"DML: {schema_name}.{table_name}"))
        file.write(set_search_path(schema_name))
        file.write(f"TRUNCATE TABLE {qualified_name(schema_name, table_name)} RESTART IDENTITY CASCADE;\n")
        file.write(
            f"COPY {qualified_name(schema_name, table_name)} "
            f"({', '.join(quote_ident(column) for column in columns)}) FROM stdin;\n"
        )

        with conn.cursor(name=f"export_{schema_name}_{table_name}", row_factory=dict_row) as cur:
            cur.itersize = 10000
            cur.execute(select_query)
            for row in cur:
                file.write("\t".join(copy_value(row[column]) for column in columns))
                file.write("\n")
                row_count += 1

        file.write("\\.\n")

    return row_count


def parse_table_arg(value: str) -> tuple[str | None, str]:
    parts = value.split(".", 1)
    if len(parts) == 2:
        return parts[0], parts[1]
    return None, value


def parse_args(argv: Iterable[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Export PostgreSQL table data as COPY-based SQL files."
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=DEFAULT_OUTPUT_DIR,
        help=f"Output directory. Default: {DEFAULT_OUTPUT_DIR}",
    )
    parser.add_argument(
        "--schema",
        help="Default schema for unqualified table names.",
    )
    parser.add_argument(
        "tables",
        nargs="*",
        default=list(DEFAULT_TABLES),
        help="Tables to export. Use table or schema.table. Defaults to ticker_master and mart_daily_price_raw.",
    )
    return parser.parse_args(list(argv))


def main(argv: Iterable[str] | None = None) -> int:
    args = parse_args(argv or sys.argv[1:])

    with connect_postgres() as conn:
        for table_arg in args.tables:
            schema_name, table_name = parse_table_arg(table_arg)
            table = find_table(conn, table_name, schema_name or args.schema)
            row_count = export_table(
                conn,
                args.output_dir,
                table["schema_name"],
                table["table_name"],
            )
            print(f"{table['schema_name']}.{table['table_name']}: {row_count} rows")

    print(f"DML exported to: {args.output_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
