from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path
from typing import Iterable

from psycopg.rows import dict_row

from postgres_connector import connect_postgres


PROJECT_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_OUTPUT_DIR = PROJECT_ROOT / "data" / "postgresql" / "sql" / "ddl"
SYSTEM_SCHEMAS = ("pg_catalog", "information_schema")


def quote_ident(value: str) -> str:
    return '"' + value.replace('"', '""') + '"'


def quote_literal(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def qualified_name(schema: str, name: str) -> str:
    return f"{quote_ident(schema)}.{quote_ident(name)}"


def safe_filename(*parts: str) -> str:
    raw = ".".join(parts)
    return re.sub(r'[<>:"/\\|?*\x00-\x1f]', "_", raw) + ".sql"


def write_sql(path: Path, sql: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(sql.rstrip() + "\n", encoding="utf-8")


def header(title: str) -> str:
    return f"-- {title}\n-- Generated by scripts/db/export_postgres_ddl.py\n\n"


def set_search_path(schema: str) -> str:
    return f"SET search_path = {quote_ident(schema)}, pg_catalog;\n\n"


def schema_filter_sql(schemas: list[str] | None, alias: str = "n") -> tuple[str, dict]:
    if schemas:
        return f"{alias}.nspname = ANY(%(schemas)s)", {"schemas": schemas}
    return (
        f"{alias}.nspname <> ALL(%(system_schemas)s) AND {alias}.nspname NOT LIKE %(pg_schema_pattern)s",
        {"system_schemas": list(SYSTEM_SCHEMAS), "pg_schema_pattern": "pg\\_%"},
    )


def fetch_relations(conn, schemas: list[str] | None) -> list[dict]:
    where_sql, params = schema_filter_sql(schemas)
    with conn.cursor(row_factory=dict_row) as cur:
        cur.execute(
            f"""
            SELECT
                c.oid,
                n.nspname AS schema_name,
                c.relname AS object_name,
                c.relkind,
                obj_description(c.oid, 'pg_class') AS object_comment
            FROM pg_class c
            JOIN pg_namespace n ON n.oid = c.relnamespace
            WHERE c.relkind IN ('r', 'p', 'v', 'm')
              AND {where_sql}
            ORDER BY n.nspname, c.relkind, c.relname
            """,
            params,
        )
        return cur.fetchall()


def fetch_columns(conn, relation_oid: int) -> list[dict]:
    with conn.cursor(row_factory=dict_row) as cur:
        cur.execute(
            """
            SELECT
                a.attnum,
                a.attname AS column_name,
                format_type(a.atttypid, a.atttypmod) AS data_type,
                a.attnotnull AS not_null,
                a.attidentity AS identity_kind,
                a.attgenerated AS generated_kind,
                pg_get_expr(d.adbin, d.adrelid) AS default_expr,
                col_description(a.attrelid, a.attnum) AS column_comment
            FROM pg_attribute a
            LEFT JOIN pg_attrdef d
              ON d.adrelid = a.attrelid
             AND d.adnum = a.attnum
            WHERE a.attrelid = %(relation_oid)s
              AND a.attnum > 0
              AND NOT a.attisdropped
            ORDER BY a.attnum
            """,
            {"relation_oid": relation_oid},
        )
        return cur.fetchall()


def fetch_table_constraints(conn, relation_oid: int) -> list[dict]:
    with conn.cursor(row_factory=dict_row) as cur:
        cur.execute(
            """
            SELECT
                conname AS constraint_name,
                contype,
                pg_get_constraintdef(oid, true) AS constraint_def,
                obj_description(oid, 'pg_constraint') AS constraint_comment
            FROM pg_constraint
            WHERE conrelid = %(relation_oid)s
              AND contype IN ('p', 'u', 'c', 'x')
            ORDER BY
                CASE contype
                    WHEN 'p' THEN 1
                    WHEN 'u' THEN 2
                    WHEN 'c' THEN 3
                    ELSE 4
                END,
                conname
            """,
            {"relation_oid": relation_oid},
        )
        return cur.fetchall()


def fetch_foreign_keys(conn, schemas: list[str] | None) -> list[dict]:
    where_sql, params = schema_filter_sql(schemas)
    with conn.cursor(row_factory=dict_row) as cur:
        cur.execute(
            f"""
            SELECT
                n.nspname AS schema_name,
                c.relname AS table_name,
                con.conname AS constraint_name,
                pg_get_constraintdef(con.oid, true) AS constraint_def,
                obj_description(con.oid, 'pg_constraint') AS constraint_comment
            FROM pg_constraint con
            JOIN pg_class c ON c.oid = con.conrelid
            JOIN pg_namespace n ON n.oid = c.relnamespace
            WHERE con.contype = 'f'
              AND {where_sql}
            ORDER BY n.nspname, c.relname, con.conname
            """,
            params,
        )
        return cur.fetchall()


def fetch_indexes(conn, schemas: list[str] | None) -> list[dict]:
    where_sql, params = schema_filter_sql(schemas, alias="ns")
    with conn.cursor(row_factory=dict_row) as cur:
        cur.execute(
            f"""
            SELECT
                ns.nspname AS schema_name,
                tbl.relname AS table_name,
                idx.relname AS index_name,
                pg_get_indexdef(idx.oid) AS index_def,
                obj_description(idx.oid, 'pg_class') AS index_comment
            FROM pg_index i
            JOIN pg_class idx ON idx.oid = i.indexrelid
            JOIN pg_class tbl ON tbl.oid = i.indrelid
            JOIN pg_namespace ns ON ns.oid = tbl.relnamespace
            WHERE {where_sql}
            ORDER BY ns.nspname, tbl.relname, idx.relname
            """,
            params,
        )
        return cur.fetchall()


def fetch_schemas(conn, schemas: list[str] | None) -> list[dict]:
    where_sql, params = schema_filter_sql(schemas)
    with conn.cursor(row_factory=dict_row) as cur:
        cur.execute(
            f"""
            SELECT
                n.oid,
                n.nspname AS schema_name,
                pg_get_userbyid(n.nspowner) AS schema_owner,
                obj_description(n.oid, 'pg_namespace') AS schema_comment
            FROM pg_namespace n
            WHERE {where_sql}
            ORDER BY n.nspname
            """,
            params,
        )
        return cur.fetchall()


def fetch_sequences(conn, schemas: list[str] | None) -> list[dict]:
    where_sql, params = schema_filter_sql(schemas)
    with conn.cursor(row_factory=dict_row) as cur:
        cur.execute(
            f"""
            SELECT
                c.oid,
                n.nspname AS schema_name,
                c.relname AS sequence_name,
                format_type(s.seqtypid, NULL) AS data_type,
                s.seqstart AS start_value,
                s.seqincrement AS increment_by,
                s.seqmin AS min_value,
                s.seqmax AS max_value,
                s.seqcache AS cache_value,
                s.seqcycle AS is_cycle,
                pg_get_userbyid(c.relowner) AS sequence_owner,
                obj_description(c.oid, 'pg_class') AS sequence_comment,
                owned_ns.nspname AS owned_schema_name,
                owned_table.relname AS owned_table_name,
                owned_attr.attname AS owned_column_name
            FROM pg_class c
            JOIN pg_namespace n ON n.oid = c.relnamespace
            JOIN pg_sequence s ON s.seqrelid = c.oid
            LEFT JOIN pg_depend dep
              ON dep.classid = 'pg_class'::regclass
             AND dep.objid = c.oid
             AND dep.objsubid = 0
             AND dep.deptype = 'a'
            LEFT JOIN pg_class owned_table ON owned_table.oid = dep.refobjid
            LEFT JOIN pg_namespace owned_ns ON owned_ns.oid = owned_table.relnamespace
            LEFT JOIN pg_attribute owned_attr
              ON owned_attr.attrelid = dep.refobjid
             AND owned_attr.attnum = dep.refobjsubid
            WHERE c.relkind = 'S'
              AND {where_sql}
            ORDER BY n.nspname, c.relname
            """,
            params,
        )
        return cur.fetchall()


def fetch_functions(conn, schemas: list[str] | None) -> list[dict]:
    where_sql, params = schema_filter_sql(schemas)
    with conn.cursor(row_factory=dict_row) as cur:
        cur.execute(
            f"""
            SELECT
                p.oid,
                n.nspname AS schema_name,
                p.proname AS function_name,
                pg_get_function_identity_arguments(p.oid) AS identity_args,
                pg_get_functiondef(p.oid) AS function_def,
                pg_get_userbyid(p.proowner) AS function_owner,
                obj_description(p.oid, 'pg_proc') AS function_comment
            FROM pg_proc p
            JOIN pg_namespace n ON n.oid = p.pronamespace
            WHERE {where_sql}
            ORDER BY n.nspname, p.proname, pg_get_function_identity_arguments(p.oid)
            """,
            params,
        )
        return cur.fetchall()


def fetch_triggers(conn, schemas: list[str] | None) -> list[dict]:
    where_sql, params = schema_filter_sql(schemas)
    with conn.cursor(row_factory=dict_row) as cur:
        cur.execute(
            f"""
            SELECT
                t.oid,
                n.nspname AS schema_name,
                c.relname AS table_name,
                t.tgname AS trigger_name,
                pg_get_triggerdef(t.oid, true) AS trigger_def,
                obj_description(t.oid, 'pg_trigger') AS trigger_comment
            FROM pg_trigger t
            JOIN pg_class c ON c.oid = t.tgrelid
            JOIN pg_namespace n ON n.oid = c.relnamespace
            WHERE NOT t.tgisinternal
              AND {where_sql}
            ORDER BY n.nspname, c.relname, t.tgname
            """,
            params,
        )
        return cur.fetchall()


def render_table(conn, relation: dict) -> str:
    columns = fetch_columns(conn, relation["oid"])
    constraints = fetch_table_constraints(conn, relation["oid"])
    lines: list[str] = []

    for column in columns:
        line = f"    {quote_ident(column['column_name'])} {column['data_type']}"
        if column["generated_kind"] == "s":
            line += f" GENERATED ALWAYS AS ({column['default_expr']}) STORED"
        elif column["identity_kind"] == "a":
            line += " GENERATED ALWAYS AS IDENTITY"
        elif column["identity_kind"] == "d":
            line += " GENERATED BY DEFAULT AS IDENTITY"
        elif column["default_expr"] is not None:
            line += f" DEFAULT {column['default_expr']}"
        if column["not_null"]:
            line += " NOT NULL"
        lines.append(line)

    for constraint in constraints:
        lines.append(
            f"    CONSTRAINT {quote_ident(constraint['constraint_name'])} "
            f"{constraint['constraint_def']}"
        )

    relation_type = "TABLE" if relation["relkind"] == "r" else "TABLE"
    sql = header(f"{relation_type}: {relation['schema_name']}.{relation['object_name']}")
    sql += f"CREATE {relation_type} {qualified_name(relation['schema_name'], relation['object_name'])} (\n"
    sql += ",\n".join(lines)
    sql += "\n);\n"
    return sql


def render_view(conn, relation: dict) -> str:
    with conn.cursor(row_factory=dict_row) as cur:
        cur.execute(
            "SELECT pg_get_viewdef(%(relation_oid)s, true) AS view_def",
            {"relation_oid": relation["oid"]},
        )
        view_def = cur.fetchone()["view_def"].rstrip().rstrip(";")

    object_name = qualified_name(relation["schema_name"], relation["object_name"])
    if relation["relkind"] == "m":
        create_sql = f"CREATE MATERIALIZED VIEW {object_name} AS\n{view_def};\n"
        title = f"MATERIALIZED VIEW: {relation['schema_name']}.{relation['object_name']}"
    else:
        create_sql = f"CREATE OR REPLACE VIEW {object_name} AS\n{view_def};\n"
        title = f"VIEW: {relation['schema_name']}.{relation['object_name']}"
    return header(title) + set_search_path(relation["schema_name"]) + create_sql


def render_schema(schema: dict) -> str:
    schema_name = quote_ident(schema["schema_name"])
    sql = header(f"SCHEMA: {schema['schema_name']}")
    sql += f"CREATE SCHEMA IF NOT EXISTS {schema_name};\n"
    sql += f"ALTER SCHEMA {schema_name} OWNER TO {quote_ident(schema['schema_owner'])};\n"
    if schema["schema_comment"]:
        sql += f"\nCOMMENT ON SCHEMA {schema_name} IS {quote_literal(schema['schema_comment'])};\n"
    return sql


def render_sequence(sequence: dict) -> str:
    sequence_name = qualified_name(sequence["schema_name"], sequence["sequence_name"])
    sql = header(f"SEQUENCE: {sequence['schema_name']}.{sequence['sequence_name']}")
    sql += (
        f"CREATE SEQUENCE {sequence_name}\n"
        f"    AS {sequence['data_type']}\n"
        f"    START WITH {sequence['start_value']}\n"
        f"    INCREMENT BY {sequence['increment_by']}\n"
        f"    MINVALUE {sequence['min_value']}\n"
        f"    MAXVALUE {sequence['max_value']}\n"
        f"    CACHE {sequence['cache_value']}"
    )
    if sequence["is_cycle"]:
        sql += "\n    CYCLE"
    sql += ";\n"
    sql += f"ALTER SEQUENCE {sequence_name} OWNER TO {quote_ident(sequence['sequence_owner'])};\n"

    if sequence["owned_table_name"] and sequence["owned_column_name"]:
        owned_column = (
            f"{qualified_name(sequence['owned_schema_name'], sequence['owned_table_name'])}."
            f"{quote_ident(sequence['owned_column_name'])}"
        )
        sql += f"ALTER SEQUENCE {sequence_name} OWNED BY {owned_column};\n"

    if sequence["sequence_comment"]:
        sql += f"\nCOMMENT ON SEQUENCE {sequence_name} IS {quote_literal(sequence['sequence_comment'])};\n"

    return sql


def render_function(function: dict) -> str:
    function_name = qualified_name(function["schema_name"], function["function_name"])
    sql = header(
        f"FUNCTION: {function['schema_name']}.{function['function_name']}({function['identity_args']})"
    )
    sql += set_search_path(function["schema_name"])
    sql += function["function_def"].rstrip().rstrip(";") + ";\n"
    sql += (
        f"ALTER FUNCTION {function_name}({function['identity_args']}) "
        f"OWNER TO {quote_ident(function['function_owner'])};\n"
    )
    if function["function_comment"]:
        sql += (
            f"\nCOMMENT ON FUNCTION {function_name}({function['identity_args']}) "
            f"IS {quote_literal(function['function_comment'])};\n"
        )
    return sql


def render_trigger(trigger: dict) -> str:
    sql = header(
        f"TRIGGER: {trigger['schema_name']}.{trigger['table_name']}.{trigger['trigger_name']}"
    )
    sql += set_search_path(trigger["schema_name"])
    sql += trigger["trigger_def"].rstrip().rstrip(";") + ";\n"
    if trigger["trigger_comment"]:
        table_name = qualified_name(trigger["schema_name"], trigger["table_name"])
        sql += (
            f"\nCOMMENT ON TRIGGER {quote_ident(trigger['trigger_name'])} "
            f"ON {table_name} IS {quote_literal(trigger['trigger_comment'])};\n"
        )
    return sql


def comment_statements_for_relation(conn, relation: dict) -> list[str]:
    statements: list[str] = []
    object_type = "VIEW" if relation["relkind"] == "v" else "MATERIALIZED VIEW" if relation["relkind"] == "m" else "TABLE"
    relation_name = qualified_name(relation["schema_name"], relation["object_name"])

    if relation["object_comment"]:
        statements.append(
            f"COMMENT ON {object_type} {relation_name} IS {quote_literal(relation['object_comment'])};"
        )

    for column in fetch_columns(conn, relation["oid"]):
        if column["column_comment"]:
            statements.append(
                f"COMMENT ON COLUMN {relation_name}.{quote_ident(column['column_name'])} "
                f"IS {quote_literal(column['column_comment'])};"
            )

    for constraint in fetch_table_constraints(conn, relation["oid"]):
        if constraint["constraint_comment"]:
            statements.append(
                f"COMMENT ON CONSTRAINT {quote_ident(constraint['constraint_name'])} "
                f"ON {relation_name} IS {quote_literal(constraint['constraint_comment'])};"
            )

    return statements


def write_comment_file(conn, output_dir: Path, relation: dict) -> bool:
    statements = comment_statements_for_relation(conn, relation)
    if not statements:
        return False

    filename = safe_filename(relation["schema_name"], relation["object_name"])
    write_sql(
        output_dir / "comments" / filename,
        header(f"COMMENTS: {relation['schema_name']}.{relation['object_name']}")
        + "\n".join(statements)
        + "\n",
    )
    return True


def export_ddl(output_dir: Path, schemas: list[str] | None) -> dict[str, int]:
    counts = {
        "schemas": 0,
        "tables": 0,
        "views": 0,
        "sequences": 0,
        "indexes": 0,
        "foreign_keys": 0,
        "functions": 0,
        "triggers": 0,
        "comments": 0,
    }

    with connect_postgres() as conn:
        for schema in fetch_schemas(conn, schemas):
            filename = safe_filename(schema["schema_name"])
            write_sql(output_dir / "schemas" / filename, render_schema(schema))
            counts["schemas"] += 1

        relations = fetch_relations(conn, schemas)

        for relation in relations:
            if relation["relkind"] in ("r", "p"):
                filename = safe_filename(relation["schema_name"], relation["object_name"])
                write_sql(output_dir / "tables" / filename, render_table(conn, relation))
                counts["tables"] += 1
            elif relation["relkind"] in ("v", "m"):
                filename = safe_filename(relation["schema_name"], relation["object_name"])
                write_sql(output_dir / "views" / filename, render_view(conn, relation))
                counts["views"] += 1

            if write_comment_file(conn, output_dir, relation):
                counts["comments"] += 1

        for sequence in fetch_sequences(conn, schemas):
            filename = safe_filename(sequence["schema_name"], sequence["sequence_name"])
            write_sql(output_dir / "sequences" / filename, render_sequence(sequence))
            counts["sequences"] += 1

        for index in fetch_indexes(conn, schemas):
            filename = safe_filename(index["schema_name"], index["table_name"], index["index_name"])
            sql = header(f"INDEX: {index['schema_name']}.{index['index_name']}")
            sql += index["index_def"].rstrip().rstrip(";") + ";\n"
            if index["index_comment"]:
                sql += (
                    f"\nCOMMENT ON INDEX {qualified_name(index['schema_name'], index['index_name'])} "
                    f"IS {quote_literal(index['index_comment'])};\n"
                )
            write_sql(output_dir / "indexes" / filename, sql)
            counts["indexes"] += 1

        for foreign_key in fetch_foreign_keys(conn, schemas):
            filename = safe_filename(
                foreign_key["schema_name"],
                foreign_key["table_name"],
                foreign_key["constraint_name"],
            )
            table_name = qualified_name(foreign_key["schema_name"], foreign_key["table_name"])
            sql = header(
                f"FOREIGN KEY: {foreign_key['schema_name']}."
                f"{foreign_key['table_name']}.{foreign_key['constraint_name']}"
            )
            sql += set_search_path(foreign_key["schema_name"])
            sql += (
                f"ALTER TABLE ONLY {table_name}\n"
                f"    ADD CONSTRAINT {quote_ident(foreign_key['constraint_name'])} "
                f"{foreign_key['constraint_def']};\n"
            )
            if foreign_key["constraint_comment"]:
                sql += (
                    f"\nCOMMENT ON CONSTRAINT {quote_ident(foreign_key['constraint_name'])} "
                    f"ON {table_name} IS {quote_literal(foreign_key['constraint_comment'])};\n"
                )
            write_sql(output_dir / "foreign_keys" / filename, sql)
            counts["foreign_keys"] += 1

        for function in fetch_functions(conn, schemas):
            filename = safe_filename(
                function["schema_name"],
                function["function_name"],
                function["identity_args"] or "no_args",
            )
            write_sql(output_dir / "functions" / filename, render_function(function))
            counts["functions"] += 1

        for trigger in fetch_triggers(conn, schemas):
            filename = safe_filename(
                trigger["schema_name"],
                trigger["table_name"],
                trigger["trigger_name"],
            )
            write_sql(output_dir / "triggers" / filename, render_trigger(trigger))
            counts["triggers"] += 1

    return counts


def parse_args(argv: Iterable[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Export PostgreSQL DDL into one SQL file per database object."
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=DEFAULT_OUTPUT_DIR,
        help=f"Output directory. Default: {DEFAULT_OUTPUT_DIR}",
    )
    parser.add_argument(
        "--schema",
        action="append",
        dest="schemas",
        help="Schema to export. Can be specified multiple times. Defaults to all non-system schemas.",
    )
    return parser.parse_args(list(argv))


def main(argv: Iterable[str] | None = None) -> int:
    args = parse_args(argv or sys.argv[1:])
    counts = export_ddl(args.output_dir, args.schemas)

    print(f"DDL exported to: {args.output_dir}")
    for key, value in counts.items():
        print(f"{key}: {value}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
