-- TABLE: stock_analysis.mart_daily_price_raw
-- Generated by scripts/db/export_postgres_ddl.py

CREATE TABLE "stock_analysis"."mart_daily_price_raw" (
    "id" bigint DEFAULT nextval('mart_daily_price_raw_id_seq'::regclass) NOT NULL,
    "ticker" text,
    "trade_date" text,
    "close_price" text,
    "open_price" text,
    "high_price" text,
    "low_price" text,
    "volume" text,
    "change_rate" text,
    "created_at" timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "mart_daily_price_raw_pkey" PRIMARY KEY (id)
);
