-- TABLE: stock_analysis.mart_daily_price
-- Generated by scripts/db/export_postgres_ddl.py

CREATE TABLE "stock_analysis"."mart_daily_price" (
    "id" bigint DEFAULT nextval('mart_daily_price_id_seq'::regclass) NOT NULL,
    "created_at" timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "ticker" character varying(20) NOT NULL,
    "trade_date" date NOT NULL,
    "open_price" numeric(18,4) NOT NULL,
    "high_price" numeric(18,4) NOT NULL,
    "low_price" numeric(18,4) NOT NULL,
    "close_price" numeric(18,4) NOT NULL,
    "volume" bigint,
    "change_rate_pct" numeric(10,4),
    CONSTRAINT "mart_daily_price_pkey" PRIMARY KEY (id),
    CONSTRAINT "uk_mart_daily_price_ticker_trade_date" UNIQUE (ticker, trade_date),
    CONSTRAINT "chk_mart_daily_price_price_range" CHECK (high_price >= low_price),
    CONSTRAINT "chk_mart_daily_price_volume_nonnegative" CHECK (volume IS NULL OR volume >= 0)
);
