-- TABLE: stock_analysis.ticker_master
-- Generated by scripts/db/export_postgres_ddl.py

CREATE TABLE "stock_analysis"."ticker_master" (
    "id" integer DEFAULT nextval('ticker_master_id_seq'::regclass) NOT NULL,
    "created_at" timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "ticker" character varying(20) NOT NULL,
    "company_name" character varying(255) NOT NULL,
    "market_product_category" character varying(100) NOT NULL,
    "industry_33_code" character varying(10) DEFAULT NULL::character varying,
    "industry_33_name" character varying(100) DEFAULT NULL::character varying,
    "industry_17_code" character varying(10) DEFAULT NULL::character varying,
    "industry_17_name" character varying(100) DEFAULT NULL::character varying,
    "scale_code" character varying(10) DEFAULT NULL::character varying,
    "scale_category" character varying(100) DEFAULT NULL::character varying,
    "listing_date" date,
    "market_cap" bigint,
    "is_target" character(1) DEFAULT NULL::bpchar,
    CONSTRAINT "ticker_master_pkey" PRIMARY KEY (id),
    CONSTRAINT "ticker_master_ticker_key" UNIQUE (ticker),
    CONSTRAINT "chk_ticker_master_company_name_not_blank" CHECK (btrim(company_name::text) <> ''::text),
    CONSTRAINT "chk_ticker_master_market_product_category_not_blank" CHECK (btrim(market_product_category::text) <> ''::text),
    CONSTRAINT "chk_ticker_master_ticker_not_blank" CHECK (btrim(ticker::text) <> ''::text)
);
