-- SEQUENCE: stock_analysis.ticker_master_id_seq
-- Generated by scripts/db/export_postgres_ddl.py

CREATE SEQUENCE "stock_analysis"."ticker_master_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 2147483647
    CACHE 1;
ALTER SEQUENCE "stock_analysis"."ticker_master_id_seq" OWNER TO "postgres";
ALTER SEQUENCE "stock_analysis"."ticker_master_id_seq" OWNED BY "stock_analysis"."ticker_master"."id";
