-- COMMENTS: stock_analysis.mart_daily_price
-- Generated by scripts/db/export_postgres_ddl.py

COMMENT ON TABLE "stock_analysis"."mart_daily_price" IS '銘柄の日足価格データ';
COMMENT ON COLUMN "stock_analysis"."mart_daily_price"."id" IS '主キー';
COMMENT ON COLUMN "stock_analysis"."mart_daily_price"."created_at" IS 'レコード作成日時';
COMMENT ON COLUMN "stock_analysis"."mart_daily_price"."updated_at" IS 'レコード更新日時';
COMMENT ON COLUMN "stock_analysis"."mart_daily_price"."ticker" IS '銘柄コード（ticker）';
COMMENT ON COLUMN "stock_analysis"."mart_daily_price"."trade_date" IS '取引日';
COMMENT ON COLUMN "stock_analysis"."mart_daily_price"."open_price" IS '始値';
COMMENT ON COLUMN "stock_analysis"."mart_daily_price"."high_price" IS '高値';
COMMENT ON COLUMN "stock_analysis"."mart_daily_price"."low_price" IS '安値';
COMMENT ON COLUMN "stock_analysis"."mart_daily_price"."close_price" IS '終値';
COMMENT ON COLUMN "stock_analysis"."mart_daily_price"."volume" IS '出来高';
COMMENT ON COLUMN "stock_analysis"."mart_daily_price"."change_rate_pct" IS '前日比変化率（%）（例: 1.23 = +1.23%）';
