-- COMMENTS: stock_analysis.ticker_master
-- Generated by scripts/db/export_postgres_ddl.py

COMMENT ON TABLE "stock_analysis"."ticker_master" IS '銘柄マスタ';
COMMENT ON COLUMN "stock_analysis"."ticker_master"."id" IS '主キー';
COMMENT ON COLUMN "stock_analysis"."ticker_master"."created_at" IS 'レコード作成日時';
COMMENT ON COLUMN "stock_analysis"."ticker_master"."updated_at" IS 'レコード更新日時';
COMMENT ON COLUMN "stock_analysis"."ticker_master"."ticker" IS '銘柄コード（ticker）';
COMMENT ON COLUMN "stock_analysis"."ticker_master"."company_name" IS '銘柄名';
COMMENT ON COLUMN "stock_analysis"."ticker_master"."market_product_category" IS '市場・商品区分';
COMMENT ON COLUMN "stock_analysis"."ticker_master"."industry_33_code" IS '33業種コード';
COMMENT ON COLUMN "stock_analysis"."ticker_master"."industry_33_name" IS '33業種区分';
COMMENT ON COLUMN "stock_analysis"."ticker_master"."industry_17_code" IS '17業種コード';
COMMENT ON COLUMN "stock_analysis"."ticker_master"."industry_17_name" IS '17業種区分';
COMMENT ON COLUMN "stock_analysis"."ticker_master"."scale_code" IS '規模コード';
COMMENT ON COLUMN "stock_analysis"."ticker_master"."scale_category" IS '規模区分';
COMMENT ON COLUMN "stock_analysis"."ticker_master"."listing_date" IS '上場日';
COMMENT ON COLUMN "stock_analysis"."ticker_master"."market_cap" IS '時価総額（円）';
COMMENT ON COLUMN "stock_analysis"."ticker_master"."is_target" IS '分析対象銘柄';
