-- FUNCTION: stock_analysis.fnc_set_updated_at()
-- Generated by scripts/db/export_postgres_ddl.py

SET search_path = "stock_analysis", pg_catalog;

CREATE OR REPLACE FUNCTION stock_analysis.fnc_set_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$function$;
ALTER FUNCTION "stock_analysis"."fnc_set_updated_at"() OWNER TO "postgres";
