-- INDEX: stock_analysis.uk_mart_daily_price_ticker_trade_date
-- Generated by scripts/db/export_postgres_ddl.py

CREATE UNIQUE INDEX uk_mart_daily_price_ticker_trade_date ON stock_analysis.mart_daily_price USING btree (ticker, trade_date);
