-- INDEX: stock_analysis.idx_ticker_master_market_product_category
-- Generated by scripts/db/export_postgres_ddl.py

CREATE INDEX idx_ticker_master_market_product_category ON stock_analysis.ticker_master USING btree (market_product_category);
