-- INDEX: stock_analysis.idx_mart_daily_price_feature_ticker
-- Generated by scripts/db/export_postgres_ddl.py

CREATE INDEX idx_mart_daily_price_feature_ticker ON stock_analysis.mart_daily_price_feature USING btree (ticker);
