-- INDEX: stock_analysis.idx_mart_daily_price_feature_date
-- Generated by scripts/db/export_postgres_ddl.py

CREATE INDEX idx_mart_daily_price_feature_date ON stock_analysis.mart_daily_price_feature USING btree (trade_date);
