-- INDEX: stock_analysis.idx_ticker_master_industry_17_code
-- Generated by scripts/db/export_postgres_ddl.py

CREATE INDEX idx_ticker_master_industry_17_code ON stock_analysis.ticker_master USING btree (industry_17_code);
