-- INDEX: stock_analysis.idx_mart_daily_price_feature_signal
-- Generated by scripts/db/export_postgres_ddl.py

CREATE INDEX idx_mart_daily_price_feature_signal ON stock_analysis.mart_daily_price_feature USING btree (is_volume_spike, is_split_event, is_up_day, is_above_ma20);
