-- INDEX: stock_analysis.mart_daily_price_raw_pkey
-- Generated by scripts/db/export_postgres_ddl.py

CREATE UNIQUE INDEX mart_daily_price_raw_pkey ON stock_analysis.mart_daily_price_raw USING btree (id);
