-- INDEX: stock_analysis.mart_daily_price_feature_ticker_trade_date_key
-- Generated by scripts/db/export_postgres_ddl.py

CREATE UNIQUE INDEX mart_daily_price_feature_ticker_trade_date_key ON stock_analysis.mart_daily_price_feature USING btree (ticker, trade_date);
