-- INDEX: stock_analysis.idx_ticker_master_industry_33_code
-- Generated by scripts/db/export_postgres_ddl.py

CREATE INDEX idx_ticker_master_industry_33_code ON stock_analysis.ticker_master USING btree (industry_33_code);
