-- INDEX: stock_analysis.ticker_master_ticker_key
-- Generated by scripts/db/export_postgres_ddl.py

CREATE UNIQUE INDEX ticker_master_ticker_key ON stock_analysis.ticker_master USING btree (ticker);
