-- TRIGGER: stock_analysis.ticker_master.trg_ticker_master_set_updated_at
-- Generated by scripts/db/export_postgres_ddl.py

SET search_path = "stock_analysis", pg_catalog;

CREATE TRIGGER trg_ticker_master_set_updated_at BEFORE UPDATE ON ticker_master FOR EACH ROW EXECUTE FUNCTION fnc_set_updated_at();
