-- TRIGGER: stock_analysis.mart_daily_price_feature.trg_mart_daily_price_feature_set_updated_at
-- Generated by scripts/db/export_postgres_ddl.py

SET search_path = "stock_analysis", pg_catalog;

CREATE TRIGGER trg_mart_daily_price_feature_set_updated_at BEFORE UPDATE ON mart_daily_price_feature FOR EACH ROW EXECUTE FUNCTION fnc_set_updated_at();
