-- TRIGGER: stock_analysis.mart_daily_price.trg_mart_daily_price_set_updated_at
-- Generated by scripts/db/export_postgres_ddl.py

SET search_path = "stock_analysis", pg_catalog;

CREATE TRIGGER trg_mart_daily_price_set_updated_at BEFORE UPDATE ON mart_daily_price FOR EACH ROW EXECUTE FUNCTION fnc_set_updated_at();
