-- SCHEMA: public
-- Generated by scripts/db/export_postgres_ddl.py

CREATE SCHEMA IF NOT EXISTS "public";
ALTER SCHEMA "public" OWNER TO "pg_database_owner";

COMMENT ON SCHEMA "public" IS 'standard public schema';
